### ISSUE TITLE
question regarding the experimental Protocol 

### ISSUE THREAD

**Issue by biannachen** [NormanGod/IMISDA#1]
Hi, I’m trying to verify my model  using the SEED-IV dataset.  I have a question about the experimental protocol for Subject-independent experiment on SEED-IV dataset (15 subjets×3 sessions×24 trials).
I would like to know the leave-one-subject-out cross-validation strategy used  is option A or option B or others.
I would appreciate it if you could help me.
Thanks and regards.

Option A:
(Each experiment uses a section as a test set, with a total of 15*3 experiments)

Option B:
(Each experiment uses three section as a test set, with a total of 15 experiments)

**Comment by NormanGod** [comment]
Hi, @biannachen
  In this paper, we use the **Option B** to fair validate our model performance, because we refer to the previous open source work [MS-MDA, MEER-NET](https://github.com/VoiceBeer/MS-MDA).
But from my opinion, both option would be correct in larger dataset. Since the EEG indivdual difference cause by the different brain situation (e.g. skull thickness, hair density, limbic system develop degree) in different people. The difference of A and B is take cross-day(session, section) inference into consideration, this **may**  be brought about by people having mental states or having different scalp states on different day. This seems be a subset of cross-subject problem.Our prior work on SEED and SEED-IV dataset, option A has performance reduction to option B. We believe it cause by the small dataset.
Some work use the Option A too, as describe in [torch-EEG](https://torcheeg.readthedocs.io/en/latest/torcheeg.model_selection.html#kfoldcrosssubject), we may use the option A in future.
![image](https://user-images.githubusercontent.com/68765654/228239739-19698aac-1dc2-4b71-809d-e5449b003c90.png)

Hope it would help you. 😀
